### ISSUE TITLE
Causing andriod apk build fail : ':app:checkDebugDuplicateClasses'. 

### ISSUE THREAD

**Issue by flutterdesign** [aboutyou/dart_packages#102]
* What went wrong:                                                      
Execution failed for task ':app:checkDebugDuplicateClasses'.            
> 1 exception was raised by workers:                                    
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-20.0.jar (com.google.guava:guava:20.0) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0)

once the pub removed, the build was successful.

**Comment by tp** [comment]
@flutterdesign We don't know what causes this exactly, but the workaround is described in https://github.com/aboutyou/dart_packages/issues/100#issuecomment-645302522 for example.

Hope this helps you to keep using the package. If not feel free to reopen.

**Comment by PiotrWpl** [comment]
@tp 
I found the root cause of this issue. It's because of google_sign_in plugin https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/android/build.gradle#L38

They are using different guava library (different package name), and because of that Gradle is not able to solve the dependencies. Either they need to upgrade to your guava version, or You need to downgrade. Probably the first solution is the proper one.

**Comment by amit-iconflux** [comment]
Add this library in your app level build.gradle

implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava' fixed it for me.
