### ISSUE TITLE
[sign_in_with_apple] Re-sign in with hide email address 

### ISSUE THREAD

**Issue by raffa-12** [aboutyou/dart_packages#140]
Hi,

After a user logs out and logs in again in the app with a hide email address, the sign in is not working because i'm getting a null email address and null username. Both are required for the `getAppleIDCredential ` function.
Can you please update the function in order to get again the correct account.
Thanks.

**Comment by HenriBeck** [comment]
This is by design and is done by Apple, we didn't make this decision that the login works this way.

For more information have a look at the code documentation of the fields from `AuthorizationCredentialAppleID `: https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/authorization_credential.dart#L55

**Comment by raffa-12** [comment]
Ok, so if the user logs in in different devices with his/her hide email address your plug in won't work correctly because the name and the email address are null.

**Comment by giorgio79** [comment]
This lib https://github.com/ananay/apple-auth mentions that " Important note: Apple will only provide you with the name and email ONCE which is when the user taps "Sign in with Apple" on your app the first time. Keep in mind that you have to store this in your database at this time! For every login after that, Apple will provide you with a unique ID that you can use to lookup the username in your database."
