### ISSUE TITLE
Credential information of email and givenName are empty for second time login

### ISSUE THREAD

**Issue by hayashi-tz** [aboutyou/dart_packages#154]
Dear Developers,

I couldn't get the email and givenName for the second time login but I got the only userIdentifier, first login can get all user credential information.

So How can I get all user credential information a second-time login?

I am looking forward to your reply and support.

Thank you very much.

**Comment by HenriBeck** [comment]
@hayashi-tz this is by design and not a limitation on our side but one on Apples side. See the [docs](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/authorization_credential.dart#L55) for the `givenName`, `familyName` or `email` on the `AuthorizationCredentialAppleID`.

**Comment by hayashi-tz** [comment]
Thank you very much @HenriBeck for your reply with noted.

**Comment by gtu-myowin** [comment]
@HenriBeck your link is broken and I can't find the file named authorization_credential.dart in the repo either. I am having the same issue. Could you please provide me the updated link? 

> @hayashi-tz this is by design and not a limitation on our side but one on Apples side. See the [docs](https://github.com/aboutyou/dart_packages/blob/master/packages/sign_in_with_apple/lib/src/authorization_credential.dart#L55) for the `givenName`, `familyName` or `email` on the `AuthorizationCredentialAppleID`.
