### ISSUE TITLE
Crash when push restart on VSCode after Signing in with Apple ID

### ISSUE THREAD

**Issue by nurassylive** [aboutyou/dart_packages#205]
Hello everybody and this SIgnInWithApple package developer team. Awesome package. But I have an issue, I don't know why it happens. The problem is when I successfully sign in using Apple ID, it crashes after I push restart button on VSCode. In my debag console appears text showing in screenshot! Please can anyone help me solving this issue? Thanks in advance!
<img width="1026" alt="Screen Shot 2021-05-08 at 5 03 57 AM" src="https://user-images.githubusercontent.com/15155392/117544018-29779e00-b041-11eb-9ace-871bb4b8672d.png">

**Comment by HenriBeck** [comment]
@nurassylive could you please provide further information such as library version, flutter version, iOS version, and the output of `flutter doctor -v`?

**Comment by rmckern** [comment]
Great flutter package! I'm getting the same error on hot restart after logging in with an appleid.

Restarted application in 1,065ms.
-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280000960
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280000960'
*** First throw call stack:
(0x1938f65b4 0x1a83757a8 0x1937f9a9c 0x1938f910c 0x1938fb6b0 0x104515354 0x10451731c 0x1045253d4 0x104523340 0x104522394 0x109af8694 0x109298038 0x10959741c 0x10953681c 0x109538ed4 0x19387108c 0x193870c88 0x1938700d8 0x193869e8c 0x1938691c0 0x1aae51734 0x1962d77e4 0x1962dd054 0x104018604 0x193525cf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001c18ef334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1c18ef334 <+8>:  b.lo   0x1c18ef354               ; <+40>
    0x1c18ef338 <+12>: pacibsp
    0x1c18ef33c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1c18ef340 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: Bad state: No element
Error handling 'serviceExtension' custom request: Bad state: No element
Lost connection to device.
Exited (sigterm)

I'm using sign_in_with_apple 3.0.0

[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/richardmckern/development/flutter
    • Framework revision 1d9032c7e1 (12 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/richardmckern/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 11 pro max (mobile) • 00008030-000231982232802E • ios            • iOS 14.5.1
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 90.0.4430.212

• No issues found!
