### ISSUE TITLE
[sign_in_with_apple] README outdated/unprecise

### ISSUE THREAD

**Issue by tomassasovsky** [aboutyou/dart_packages#242]
I'm currently trying to set up my app for Apple Sign In, but the service configuration doesn't have Domains and Subdomains nor Redirect URLs to fill in:

![Screen Shot 2021-09-23 at 19 03 39](https://user-images.githubusercontent.com/63405252/134590489-d4b7289b-f03e-4fe4-b6b0-c12771d524d9.png)

Because of this, I get this error when trying to Sign In from Android (it's also weird that it gets opened on the phone's actual browser and not on WebView)
![photo_2021-09-23 19 14 09](https://user-images.githubusercontent.com/63405252/134591109-be9c3725-1067-42df-bc4c-a2c927915f56.jpeg)

On the iOS emulator, I get this problem: #144

**Comment by tp** [comment]
> I'm currently trying to set up my app for Apple Sign In, but the service configuration doesn't have Domains and Subdomains nor Redirect URLs to fill in

That’s because you have to set up your own domain & server, which then redirect back into the app (or possibly use verified domains to open your app directly on the redirect).

So there is no general callback URL we can specify, it really depends on your client/server setup. 

As for Android not using a web view, that is really because of best practices, that we should be using either the system browser or (Chrome) Custom Tabs, to have the best performance and OS integration. (After the process completed those will be closed and the customer redirect to the app anyway.)

**Comment by tomassasovsky** [comment]
Okay, but where do I have to specify that information?

**Comment by HenriBeck** [comment]
@tomassasovsky please follow this guideline: https://help.apple.com/developer-account/?lang=en#/dev1c0e25352
