### ISSUE TITLE
Sign In with Apple in Web login failed

### ISSUE THREAD

**Issue by goodmirow-1** [aboutyou/dart_packages#336]
I wanted to try apps through web.

Code is as follows.

 
```
 final credential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        webAuthenticationOptions: WebAuthenticationOptions(
          clientId: 'kr.sheeps.nolilteo.NolilteoLogin',
          redirectUri: Uri.parse('https://fog-keen-arch.glitch.me/callbacks/sign_in_with_apple',)
        ),
      );

final signInWithAppleEndpoint = Uri(
        scheme: 'https',
        host: 'fog-keen-arch.glitch.me',
        path: '/sign_in_with_apple',
        queryParameters: <String, String>{
          'code': credential.authorizationCode,
          if (credential.givenName != null)
            'firstName': credential.givenName!,
          if (credential.familyName != null)
            'lastName': credential.familyName!,
          'useBundleId':
          !kIsWeb && (IO.Platform.isIOS || IO.Platform.isMacOS)
              ? 'true'
              : 'false',
          if (credential.state != null) 'state': credential.state!,
        },
      );
```

However, the login screen with apple id on the web does not go over even though I continue pressing the button.
It was confirmed that the url was not called even in glitch.

What's wrong with my code?

**Comment by samueladekunle** [comment]
Using the sample code in the example folder

After I entered the password on iOS, the spinner keeps spinning and nothing happens.

On android, the browser does not redirect to the app after I signed in.


<img width="273" alt="image" src="https://user-images.githubusercontent.com/27623752/204009617-422befe0-f75b-4e2c-b13d-f7febafe69e2.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/27623752/204009791-b99440e3-e650-4b12-8637-7220d6cbfa5e.png">

**Comment by darkstarx** [comment]
Is there anybody here who can fix this bug?

**Comment by HenriBeck** [comment]
So there are a few different issues mixed in together here.

---

First, replying to @goodmirow-1, your issue probably won't be in the code but in your Apple Developer configuration if it doesn't redirect.  
Please make sure to set up all the correct domains and callback URLs.  
Since this happens when trying to redirect from Apple, it's not a bug in this library. 

Please be aware that Glitch servers are not production ready. They will shut down after a while and are only used as an example in our repository.

---

@samueladekunle if the iOS bug happens on a simulator, then it's a known issue with Apple, nothing we can do about it.

About the android issue, this looks like some weird non-chrome browser that doesn't support intent links. This is a known issue and can't be avoided right now.  
See this issue for further explanation: #174

**Comment by samueladekunle** [comment]
@HenriBeck, thanks for the response. Do you mean I cannot sign in with Apple on iOS simulators?

**Comment by HenriBeck** [comment]
@samueladekunle correct

**Comment by wenrong44333** [comment]
Hi, i have similar issue with you. After few days of struggling, I finally manage to solve my issue. My issue is the `redirectUri` that I pass at `webAuthenticationOptions` is wrong, it should be the domain of my web app (https://myapp.domain.com/) instead of Firebase or Glitch or third party url. 

```
final appleCredential = await SignInWithApple.getAppleIDCredential(
        scopes: [
          AppleIDAuthorizationScopes.email,
          AppleIDAuthorizationScopes.fullName,
        ],
        state: 'origin:web',
        webAuthenticationOptions: WebAuthenticationOptions(
            clientId: appleServiceId, // 'com.mycompany.app.service'
            redirectUri: Uri.parse(appleRedirectUri,) // 'https://webapp.mydomain.com/'
        ),
      );
      final oauthCredential = OAuthProvider("apple.com").credential(
        idToken: appleCredential.identityToken,
        accessToken: appleCredential.authorizationCode,
      );
      if (oauthCredential == null) return;

      Module().showLoadingDialog(Get.context!);

      await FirebaseAuth.instance.signInWithCredential(oauthCredential);
```

Besides that, the domains and subdomains & Return URLs also need to add your web app domain at apple developers console under Certificates, Identifiers & Profiles -> Identifiers -> Services IDs.

<img width="356" alt="屏幕截图 2022-12-13 150039" src="https://user-images.githubusercontent.com/120447396/207248556-a318aa41-ca25-483e-be36-aac3647a477a.png">
