### ISSUE TITLE
Question about flutter web compatibility.

### ISSUE THREAD

**Issue by m-j-g** [aboutyou/dart_packages#90]
Hey guys, thanks for the great work.  I'm trying to research what would need to happen to implement this for flutter web (Our users aren't going to be so happy when they can't login to their account from the web).  Can you point me in the right direction or share the hurdles I might face with that?

**Comment by tp** [comment]
Hey @m-j-g,

I think the simplest way to make that work would be without Apples JS SDK (https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js), and just render the button in Flutter and then use the same URL-building logic as we do on Android:
https://github.com/aboutyou/dart_packages/blob/23679ba7e4b60d17f5ebe69f142fe94d813b7df7/packages/sign_in_with_apple/lib/src/sign_in_with_apple.dart#L198

On click of the button you would open that URL (easiest again probably redirect of the current page, a better experience might be a pop-up/new tab, so the main app doesn't have to reload upon return), and then set a route on your app as the redirect URL.

The redirect URL would need to be able to handle the POST that Apple is sending to your servers. 

You can then either handle that directly on the server (and then for example pass down a cookie and the SPA entry page), or somehow pass received POST data to the client, so it would call the same API than the native apps do.

As Apple is always redirecting through the redirect URL, I don't yet know how to make that really nice from a client API perspective (so that the same simple method could be called on all stacks).

Maybe the pop-up / new tab approach can be made to work with the final redirect URL using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to pass the data back to the Flutter app.

Let me know if that helps.

We would love to add nice web integration into this package as well :)

**Comment by m-j-g** [comment]
@tp Really appreciate you taking the time to outline that.  I think I understand how this all fits together now, I just need to dig in and start working through it.
