### ISSUE TITLE
[sign_in_with_apple] fallback to Safari web authentication on iOS versions prior to 13

### ISSUE THREAD

**Issue by eduribas** [aboutyou/dart_packages#99]
Hi, any plans to support that?

I implemented a working solution here: https://github.com/eduribas/dart_packages/commit/c543775470d3eacf437500bf9f833f097f252f3a

I basically used the same approach you used for Android sign in. Please let me know if you are interested on this solution, I'll be happy to send a pull request.

I don't see Apple talking about that, but if my app is forced to use Apple Login (because it's using Google login, for example), it would be incompatible with iOS versions prior to 13 unless I fallback the authentication to the web.

**Comment by HenriBeck** [comment]
That's a good question. Just to be clear here, I don't think it is necessary to implement sign in with apple for any iOS version below 13, as Apple doesn't mention it anywhere in their docs.
So I would be rather surprised if your App is rejected because you don't have support for sign in with apple on older iOS versions.

The share of older iOS versions (anything below 13) is also rather low and Apple users tend to update faster than for example Android ones.
With iOS 14 also on the horizon, I can only assume that the number of users on non supported iOS versions will even get smaller in the next few months.

At this point I don't think it's necessary to add support for older versions of iOS, it adds more code that has to be maintained for a rather small target group.

cc @tp

**Comment by tp** [comment]
Hey @eduribas,

as Henri said, in general and in our own app we see pretty good update curves for iOS versions, and would hence focus on iOS 13 with the smoothest integration on Apple devices.

If there comes general interest in this (e.g. because customers have devices "stuck" with older iOS versions), or because Apple would like to broaden the support, we would happily take your proposed changes.

For now I would hope we don't have to and can keep this package legacy-free for a while ;)

Thanks a lot for the suggestion though, and possibly it's useful for someone else trying to achieve this.

**Comment by eduribas** [comment]
Hi, I agree, this may be an edge case. On the app I'm working on though, where one of the main features is to use multiples devices with the same account, unfortunately many users do have iPads "stuck" on older iOS versions. In that case I couldn't afford to not support older iOS versions.

**Comment by HenriBeck** [comment]
Hey @eduribas, Sorry for the late reply. Would it be possible for you to switch to your fork where you already implemented this feature?

As previously metioned, we don't see a lot of requests for this and are therefore cautious about adding this into our library as that would mean we would also need to maintain this code.

**Comment by otopba** [comment]
Hi guys!
I think it is a really necessary feature. Because now people with iOS <13 can't sign in it at all =(

**Comment by tp** [comment]
> Because now people with iOS <13 can't sign in it at all =(

Just people with devices on older versions that they want to use with the same app.

Do you have any indication how many of your users use multiple iOS versions at the same time?

@otopba As a first measure I suppose you can try the commit linked in the first comment.

If this helps the community, we will reconsider. But TBH do you see yourself supporting iOS 12 say 6 month after iOS 14 ships this fall? Because what I most worry about after merging is not that we have the additional code today, but that removing it in the future will be much more painful for the developers than then depend on it (so it would probably be very likely that we have to keep it for 2 more years or so).

**Comment by otopba** [comment]
@tp I have an early-stage startup and I have this numbers 

![image](https://user-images.githubusercontent.com/4225279/88797310-cd2b4800-d1ab-11ea-9976-f30a05879d44.png)

- Total: 242
- ios >=13: 234
- ios <13: 8

About 3% uses ios <13. I think you are right. It is a very low percent

**Comment by eduribas** [comment]
> Hey @eduribas, Sorry for the late reply. Would it be possible for you to switch to your fork where you already implemented this feature?
> 
> As previously metioned, we don't see a lot of requests for this and are therefore cautious about adding this into our library as that would mean we would also need to maintain this code.

@HenriBeck yes, sure, I'm using my fork. After 1 month in production, 30% of the installations are on iOS < 13, so it was the right call in my case, I really needed to support older versions. I was not expecting a number this high, it may be because the app is used by doctors on older iPads stuck on older versions.

**Comment by opringle** [comment]
I've just had my flutter app rejected for not implementing apple sign in on iOS 12. The app store guidelines say that it must be included using the javascript framework:

https://developer.apple.com/forums/thread/122755?answerId=417003022#417003022

**Comment by tp** [comment]
I just read a mail notification, but it seems like the comment was removed.

Someone claimed their app was rejected for not supporting SiwA on iOS 12.

They quoted these forum posts by an Apple staff member:

> For iOS 12 and eariler, macOS 10.14 and earlier, tvOS 12 and earlier, and watchOS 5 and earlier, as well as web applications which cannot directly access Sign in with Apple JS framework, you must manually control the sign-in request as referenced here.

https://developer.apple.com/forums/thread/122755?answerId=417003022#417003022
https://developer.apple.com/forums/thread/130365

We haven't had our app rejected, but of course this would make us immediately reconsider and bring this fix upstream. Did anyone else have issues with app review around SiwA/iOS 12?

**Comment by opringle** [comment]
> I just read a mail notification, but it seems like the comment was removed.
> 
> Someone claimed their app was rejected for not supporting SiwA on iOS 12.
> 
> They quoted these forum posts by an Apple staff member:
> 
> > For iOS 12 and eariler, macOS 10.14 and earlier, tvOS 12 and earlier, and watchOS 5 and earlier, as well as web applications which cannot directly access Sign in with Apple JS framework, you must manually control the sign-in request as referenced here.
> 
> https://developer.apple.com/forums/thread/122755?answerId=417003022#417003022
> https://developer.apple.com/forums/thread/130365
> 
> We haven't had our app rejected, but of course this would make us immediately reconsider and bring this fix upstream. Did anyone else have issues with app review around SiwA/iOS 12?

I removed the post because my app contained a bug that was preventing SiwA from appearing. I assumed the app was rejected because they were reviewing on iOS 12. I fixed the bug and have since passed the review process.

That being said, the forum posts do suggest that iOS 12 devices should also handle sign in with apple.

**Comment by tp** [comment]
Thanks for clarifying @opringle. I have yet to find any report where the app really got rejected when supporting iOS 13 but not 12.

Also ABOUT YOU's app just passed review again, so I suspect that forum post is outdated, or maybe that was their intention but it's not clearly enforced.

**Comment by nicoroy2561** [comment]
Hi,
while the app won't get rejected over it, it would be nice if there was a simple line that provided a fallback for iOS 12, if all it takes is a check that opens it in the browser like it's done for android. Or if a method for directly invoking browser login was exposed, so that the developers could choose to fall back onto that if it fails otherwise while still being on an Apple system.
I have a customer with a 7-yo phone that reported me he can't login with Apple despite his device being an iPhone. They may be a minority, but if it's a small change I'd say it could be done.

Thanks for the nice plugin though, I really appreciate it :)

**Comment by tp** [comment]
> it would be nice if there was a simple line that provided a fallback for iOS 12, if all it takes is a check that opens it in the browser like it's done for android.

It's not that simple, as the Android code it written for that platform and we do need a new implementation for iOS (what the OP built already).

Also I don't think we can have a general fallback "to the browser", as there is still the platform dependent way "back to the app" that we need to handle (what is currently achieved by deep links on the mobile apps). So I think we'll have to add new platforms individually here.

> if it's a small change I'd say it could be done

As stated above, it's not super small and we can't take on the additional support burden this would entail currently (really testing on older devices for each release).

If this is important to you I suggest you just pin your dependency to the OP's branch (thanks again for that!).

Sorry to not have better news here, hope this works for you.
(And please tell us if we're totally off by assuming that most apps should not have this issue as nearly all users have devices which could run iOS 13 or later.)

**Comment by HenriBeck** [comment]
Closing this since we will not implement it in this package.
